server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Tashini4/spms_config.git
          default-label: master
          username: Tashini4


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/